import {useEffect,useRef,useState,type ReactNode} from 'react';
import type {Instance,RuntimeView} from './domain';
import {I,Logo} from './ui';
import PerchMark from './PerchMark';
import QuickSearch from './QuickSearch';
import WindowControls from './WindowControls';
function instanceAbbreviation(name:string){const compact=name.trim().replace(/\s+/g,'');return Array.from(compact).slice(0,/\p{Script=Han}/u.test(compact)?2:3).join('');}
export const navigation=[['launch','home','启动台'],['library','box','我的实例'],['discover','layers','发现整合包'],['extensions','puzzle','扩展市场'],['favorites','heart','我的收藏'],['connections','globe','模型连接'],['snapshots','shield','恢复中心'],['activity','clock','任务与活动'],['settings','settings','设置']];
export default function AppShell({children,selectedId,page,instances,onPage,onInstance,onNew,mode,runtime,busy,maximized,windowAction}:{children:ReactNode;selectedId?:string;page:string;instances:Instance[];onPage:(p:string)=>void;onInstance:(i:Instance)=>void;onNew:()=>void;mode:'desktop'|'demo';runtime:RuntimeView[];busy:boolean;maximized:boolean;windowAction:(action:string)=>void}){
 const [sidebarCollapsed,setSidebarCollapsed]=useState(false);
 const running=runtime.filter(r=>r.status==='running').length;
 const working=runtime.some(r=>['installing','starting','stopping'].includes(r.status));
 const scroll=useRef<HTMLElement>(null);useEffect(()=>{scroll.current?.scrollTo(0,0);},[page]);
 return <div className={"desktop-window native-window managed-shell"+(sidebarCollapsed?" sidebar-collapsed":"")}><div className="desktop-body"><aside id="workspace-sidebar" className="sidebar"><div className="sidebar-brand"><span className="app-symbol"><PerchMark/></span><div><b>栖点</b><small>STUDIO</small></div></div>
 <div className="sidebar-search-wrap" onFocusCapture={()=>{if(sidebarCollapsed)setSidebarCollapsed(false);}}><QuickSearch instances={instances} onOpen={onInstance}/></div><div className="nav-section">WORKSPACE</div>{navigation.slice(0,6).filter(([id])=>id!=='connections').map(([id,icon,title])=><button title={title} aria-label={title} key={id} aria-current={page===id?'page':undefined} className={'side-nav '+(page===id?'active':'')} onClick={()=>onPage(id)}><I name={icon}/><span>{title}</span>{id==='library'&&<small>{instances.length}</small>}</button>)}
 <div className="nav-section between"><span>PROJECTS</span><button className="icon-btn" title="新建实例" onClick={onNew}><I name="plus"/></button></div><div className="project-nav-list">{instances.map(instance=><button title={instance.name} aria-label={instance.name} key={instance.id} aria-current={selectedId===instance.id?'page':undefined} className={'side-nav project-nav '+(selectedId===instance.id?'active':'')} onClick={()=>onInstance(instance)}><Logo engine={instance.engine}/><b className="instance-rail-marker" aria-hidden="true">{instanceAbbreviation(instance.name)}</b><span>{instance.name}</span></button>)}</div>
 <div className="sidebar-bottom">{navigation.slice(6).map(([id,icon,title])=><button title={title} aria-label={title} key={id} className={'side-nav '+(page===id||(id==='settings'&&page==='connections')?'active':'')} onClick={()=>onPage(id)}><I name={icon}/><span>{title}</span></button>)}<div title={working?'引擎任务执行中…':busy?'正在处理…':`${running} 个工作台运行中`} className="sidebar-status" role="status" aria-live="polite"><i className={'status-dot '+(working||busy?'busy':running?'live':'')}/><span>{working?'引擎任务执行中…':busy?'正在处理…':`${running} 个工作台运行中`}</span></div></div></aside>
 <div className="workspace"><header className="workspace-header"><button type="button" className="icon-btn sidebar-toggle" title={sidebarCollapsed?'展开侧边栏':'折叠侧边栏'} aria-label={sidebarCollapsed?'展开侧边栏':'折叠侧边栏'} aria-expanded={!sidebarCollapsed} aria-controls="workspace-sidebar" onClick={()=>setSidebarCollapsed(value=>!value)}><svg className="i" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="3"/><path d="M9 4v16"/></svg></button><div className="workspace-drag" data-tauri-drag-region><div className="breadcrumbs"><b>{navigation.find(n=>n[0]===page)?.[2]??'实例配置'}</b></div></div><WindowControls maximized={maximized} onMinimize={()=>windowAction('minimize')} onMaximize={()=>windowAction('maximize')} onClose={()=>windowAction('close')}/></header><main ref={scroll} className="workspace-scroll"><div className="page-content">{mode==='demo'&&<div className="notice">浏览器演示 · 数据仅在内存中，刷新即重置。密钥只能在桌面端保存。</div>}{children}</div></main></div></div>
</div>;
}
