import {useEffect,useState} from 'react';
import {errorText,type Gateway,type Instance,type Recipe} from './domain';
import {Button} from './ui';
import {recipeChanges} from './PackagePanel';
import PiPackageChanges from './PiPackageChanges';

export default function InstalledExtensions({gateway,instances,onOpen}:{gateway:Gateway;instances:Instance[];onOpen:(instance:Instance)=>void}) {
 const [target,setTarget]=useState('');
 return <section><label className="field"><span>管理哪个实例的扩展</span><select className="input" value={target} onChange={e=>setTarget(e.target.value)}><option value="">选择实例</option>{instances.map(instance=><option key={instance.id} value={instance.id}>{instance.name} · {instance.engine}</option>)}</select></label>{!instances.length?<p>还没有实例，请先创建一个工作环境。</p>:!target?<p>每个实例的扩展独立保存，请先选择目标。</p>:instances.find(instance=>instance.id===target)&&<Resources key={target} gateway={gateway} instance={instances.find(instance=>instance.id===target)!} onOpen={onOpen}/>}</section>;
}
function Resources({gateway,instance,onOpen}:{gateway:Gateway;instance:Instance;onOpen:(instance:Instance)=>void}) {
 const [recipe,setRecipe]=useState<Recipe>(),[draft,setDraft]=useState<Recipe>();
 const [names,setNames]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[running,setRunning]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){const [data,catalog,snapshot]=await Promise.all([gateway.instancePackage(instance.id),gateway.packageCatalog(),gateway.snapshot()]);setRecipe(data.recipe);setNames(Object.fromEntries(catalog.extensions.map(item=>[item.id,item.name])));setRunning(snapshot.runtime.some(item=>item.id===instance.id&&['running','starting','stopping','installing'].includes(item.status)));}
 useEffect(()=>{void load().catch(e=>setError(errorText(e)));},[]);
 async function save(){if(!recipe||!draft)return;setBusy(true);setError('');try{await gateway.changePackage(instance.id,draft,false,recipe);await load();setDraft(undefined);setMessage('已保存，下一次启动生效；其他资源保持原样。');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <>{instance.engine==='Pi'&&gateway.mode==='desktop'&&recipe&&<PiPackageChanges id={instance.id} running={running} recipe={recipe} onChange={async()=>{await load();setDraft(undefined);}}/>}<div className="section-title"><div><h2>{instance.name} 的扩展</h2><p>扩展随实例组合保存，安装与运行状态可在实例中查看。</p></div><Button onClick={()=>onOpen(instance)}>打开实例</Button></div>{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status">{message}</p>}{running&&<p>请先停止工作台，再更改扩展。<Button disabled={busy} onClick={()=>void load().catch(e=>setError(errorText(e)))}>刷新状态</Button></p>}{!recipe&&!error&&<p role="status">正在读取实例资源…</p>}{recipe?.extensions.length===0&&<p>此实例尚未选择扩展，可到“发现”添加。</p>}{recipe?.extensions.map(item=><div className="fact" key={item.id}><div><strong>{names[item.id]??item.id}</strong><p>{item.version} · {item.enabled?'已启用':'已禁用'}</p><p className="sub">{item.id.startsWith('npm:')||item.id.startsWith('dsh-npm:')?'来源：npm 精确版本包':item.id.startsWith('local-skill-')?'来源：本机受管 Skill':'来源：栖点内置'}</p></div><div className="form-actions"><Button disabled={busy||running} onClick={()=>setDraft({...recipe,extensions:recipe.extensions.map(entry=>entry.id===item.id?{...entry,enabled:!entry.enabled}:entry)})}>{item.enabled?'禁用':'启用'}</Button><Button disabled={busy||running} onClick={()=>setDraft({...recipe,extensions:recipe.extensions.filter(entry=>entry.id!==item.id)})}>移除</Button></div></div>)}{recipe&&draft&&<section aria-label="确认扩展变更"><h3>确认变更 · {instance.name}</h3>{recipeChanges(recipe,draft).map(line=><p key={line}>{line}</p>)}<p>变更前自动创建恢复点，模型连接保持绑定。</p><div className="form-actions"><Button disabled={busy} onClick={()=>setDraft(undefined)}>取消</Button><Button primary disabled={busy||running} onClick={()=>void save()}>{busy?'正在保存…':'确认变更'}</Button></div></section>}</>;
}
