import Section from './Section';
import VersionCatalog from './VersionCatalog';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {compatibility,errorText,type Engine,type Gateway,type Instance,type Snapshot,type Recipe,type ModelConnection} from './domain';
import {invoke} from '@tauri-apps/api/core';
import {Button} from './ui';
import {pendingCreation,rememberCreation,forgetCreation} from './pendingPackCreation';
export type InstanceDraft={name:string;engine:Engine;projectPath:string;connectionId:string;profileId?:string};
export default function InstanceForm({instance,draft,recipe,data,gateway,onSaved,onCancel,onConnections,onDraftChange,onBusyChange}:{instance?:Instance;recipe?:Recipe;draft?:InstanceDraft;data:Snapshot;gateway:Gateway;onSaved:(s:Snapshot,instanceId?:string)=>void;onCancel:()=>void;onConnections:(draft:InstanceDraft)=>void;onDraftChange?:(draft:InstanceDraft)=>void;onBusyChange?:(busy:boolean)=>void}){
 const [resume]=useState(()=>{if(!recipe||instance)return undefined;try{return pendingCreation(localStorage,recipe);}catch{return undefined;}});
 draft=draft??resume?.draft;
 function connectionIssue(target:Engine,connection:ModelConnection){return compatibility(target,connection)??(recipe&&!recipe.modelProtocols.includes(connection.protocol)?'此整合包不支持该连接的接口协议':null);}
 const [browseVersions,setBrowseVersions]=useState(false);
 const [profilesError,setProfilesError]=useState('');
 const [profiles,setProfiles]=useState<{id:string;engine:Engine;dependencies:Record<string,string>}[]>([]);
 const [profileId,setProfileId]=useState(draft?.profileId??instance?.profileId??recipe?.profileId??'');
 async function loadProfiles(){setProfilesError('');try{setProfiles(await invoke<typeof profiles>('resolved_profiles'));}catch(e){setProfilesError(errorText(e));}}
 useEffect(()=>{if(gateway.mode==='desktop')void loadProfiles();},[]);
 const [name,setName]=useState(draft?.name??instance?.name??recipe?.name??'');const [engine,setEngine]=useState<Engine>(draft?.engine??instance?.engine??recipe?.engine??'DSH');
 const [path,setPath]=useState(draft?.projectPath??instance?.projectPath??'');const [connectionId,setConnectionId]=useState(draft?.connectionId??(instance ? (instance.connectionId??'') : (data.connections.find(c=>!connectionIssue(recipe?.engine??'DSH',c))?.id??'')));
 const [busy,setBusy]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState('');const last=useRef({signature:resume?.signature??'',operationId:resume?.operationId??''});
 const draftListener=useRef(onDraftChange),busyListener=useRef(onBusyChange);draftListener.current=onDraftChange;busyListener.current=onBusyChange;
 useEffect(()=>{draftListener.current?.({name,engine,projectPath:path,connectionId,profileId});},[name,engine,path,connectionId,profileId]);
 useEffect(()=>{busyListener.current?.(busy);return()=>busyListener.current?.(false);},[busy]);
 async function pick(){setBusy(true);setError('');try{const path=await gateway.pickProject();if(path)setPath(path);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;const connection=data.connections.find(c=>c.id===connectionId);const issue=connection?connectionIssue(engine,connection):connectionId?'所选模型连接已不存在，请重新选择。':null;if(issue){setError(issue);return;}setBusy(true);setSubmitting(true);setError('');const fields={profileId:profileId||undefined,id:instance?.id??null,expectedRevision:instance?.revision??null,name,engine,projectPath:path,connectionId:connectionId||null};const signature=JSON.stringify({fields,recipe});if(signature!==last.current.signature)last.current={signature,operationId:crypto.randomUUID()};try{if(recipe)rememberCreation(localStorage,{recipe:JSON.stringify(recipe),draft:{name,engine,projectPath:path,connectionId,profileId},...last.current});const next=recipe?await invoke<Snapshot>('create_pack_instance',{input:{...fields,operationId:last.current.operationId},recipe}):await gateway.saveInstance({...fields,operationId:last.current.operationId});const savedId=next.tasks.find(task=>task.id===last.current.operationId)?.entityId??instance?.id;if(recipe){try{forgetCreation(localStorage,last.current.operationId);}catch{/* Creation succeeded; a retained retry is idempotent. */}}onSaved(next,savedId);}catch(e){setError(errorText(e));}finally{setBusy(false);setSubmitting(false);}}
 const preparesResources=!!recipe?.workshop?.length;
 const preparingId=data.tasks.find(task=>task.id===last.current.operationId)?.entityId;
 return <form className="editor-form" onSubmit={submit}><h2>{instance?'编辑实例':'新建实例'}</h2><p>项目目录保留在原位置，实例配置独立保存。</p>{resume&&<p role="status">已恢复此整合包未完成的创建。保持原名称、目录和连接重试，会继续原实例；修改这些内容将创建另一个实例。</p>}<fieldset disabled={busy}>
 <label className="field"><span>实例名称</span><input autoFocus className="input" required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="例如：日常开发"/></label>
 <label className="field"><span>引擎</span><select className="input" disabled={!!instance||!!recipe} value={engine} onChange={e=>{const next=e.target.value as Engine;setEngine(next);setProfileId('');if(!data.connections.some(c=>c.id===connectionId&&!connectionIssue(next,c)))setConnectionId(data.connections.find(c=>!connectionIssue(next,c))?.id??'');}}><option value="DSH">DSH</option><option value="Pi">Pi</option></select></label>
 {!instance&&!recipe&&<Section description="默认沿用推荐组合，需要历史版或预览版时再调整。" className="optional-section" title={<>版本 · {profileId?'已选择固定组合':'推荐组合'}</>}><label className="field"><span>版本组合</span><select className="input" value={profileId} onChange={e=>setProfileId(e.target.value)}><option value="">推荐的已验证组合</option>{profiles.filter(p=>p.engine===engine).map(p=><option key={p.id} value={p.id}>{Object.entries(p.dependencies).map(([name,version])=>`${name} ${version}`).join(' / ')} · 已锁定，待运行验证</option>)}</select></label><Button onClick={()=>setBrowseVersions(!browseVersions)}>{browseVersions?'收起版本目录':'浏览其他版本'}</Button>{browseVersions&&<VersionCatalog engine={engine} onSelected={id=>{setProfileId(id);void loadProfiles();setBrowseVersions(false);}}/>}</Section>}
 <label className="field"><span>项目目录</span><span className="path-input"><input className="input" required value={path} onChange={e=>setPath(e.target.value)} placeholder="输入已有项目的绝对路径"/><Button disabled={gateway.mode==='demo'} onClick={pick}>选择目录</Button></span></label>
 <label className="field"><span>模型连接</span><select className="input" value={connectionId} onChange={e=>setConnectionId(e.target.value)}><option value="">{recipe?'选择兼容的已有连接':'暂不绑定，稍后配置'}</option>{data.connections.map(c=><option key={c.id} value={c.id} disabled={!!connectionIssue(engine,c)}>{c.name}{connectionIssue(engine,c)?` · ${connectionIssue(engine,c)}`:''}</option>)}</select></label>
 {!data.connections.some(c=>!connectionIssue(engine,c))&&<p className="sub">{recipe?'此组合需要兼容连接。请先到“管理模型连接”添加一次，返回后继续创建。':'还没有适合此引擎的连接。可以先保存实例，之后在“模型连接”中添加。'}</p>}
 <Button onClick={()=>onConnections({name,engine,projectPath:path,connectionId,profileId})}>管理模型连接</Button><p className="sub">{profileId?`固定组合：${profiles.find(p=>p.id===profileId)?Object.entries(profiles.find(p=>p.id===profileId)!.dependencies).map(([name,version])=>`${name} ${version}`).join(' / '):profileId}`:'使用推荐的已验证版本组合'}。{preparesResources?'创建时会下载并准备固定依赖及工坊资源，完成后可在实例页面启动。':'保存后可在实例页面安装和启动。'}</p>
 {profilesError&&<p role="status">版本组合读取失败：{profilesError} <Button onClick={()=>void loadProfiles()}>重新读取</Button></p>}
 </fieldset>{submitting&&preparesResources&&<p role="status">正在创建实例并准备组合，首次下载可能需要几分钟。取消或失败后可保留此表单重试。</p>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions">{submitting&&preparesResources&&preparingId&&<Button onClick={()=>void gateway.cancelEngine(preparingId).catch(e=>setError(errorText(e)))}>取消组合准备</Button>}<Button disabled={busy} onClick={onCancel}>取消</Button><button className="btn primary" type="submit" disabled={busy}>{busy?(submitting&&preparesResources?'正在准备组合…':'正在保存…'):(preparesResources?'创建并准备组合':'保存实例')}</button></div></form>;
}
