import {connectionIssue as modelConnectionIssue} from './runtimeReadiness';
import {useState} from 'react';
import {runtimeLabels,type Gateway,type Snapshot,type Instance} from './domain';
import {Button,I,IconButton,Logo,Mountain} from './ui';
import InstanceRuntime from './InstanceRuntime';

export default function LaunchPage({data,gateway,recentId,onSelect,onOpen,onNew,onRefresh,onConnections}:{data:Snapshot;gateway:Gateway;recentId:string;onSelect:(id:string)=>void;onOpen:(instance:Instance)=>void;onNew:()=>void;onRefresh:()=>Promise<void>;onConnections:(instance:Instance)=>void}){
 const [filter,setFilter]=useState('全部');
 const current=data.instances.find(i=>i.id===recentId)??data.instances[0];
 const state=(i:Instance)=>data.runtime.find(r=>r.id===i.id);
 const missingConnection=(i:Instance)=>!data.connections.some(c=>c.id===i.connectionId);
 const connectionIssue=(i:Instance)=>modelConnectionIssue(i,data.connections.find(c=>c.id===i.connectionId));
 const needs=(i:Instance)=>!i.projectExists||!!connectionIssue(i)||state(i)?.status==='failed';
 const list=data.instances.filter(i=>filter==='全部'||(filter==='运行中'?state(i)?.status==='running':needs(i)));
 const runtime=(i:Instance,iconOnly=false)=><InstanceRuntime key={i.id} compact iconOnly={iconOnly} instance={i} connection={data.connections.find(c=>c.id===i.connectionId)} runtime={state(i)} gateway={gateway} onRefresh={onRefresh} onConnections={()=>onConnections(i)}/>;
 return <><div className="page-heading"><div><h1>准备好了，就开始。</h1><p>选择一个熟悉的环境，继续上次的灵感。</p></div><Button icon="plus" onClick={onNew}>新建实例</Button></div><section className="launch-hero"><div className="hero-copy"><h2>工具各有所长，<br/>工作自有节奏。</h2><p>把引擎、插件和习惯，安放在自己的工作空间。</p><div className="hero-action">{current?runtime(current):<Button primary icon="plus" onClick={onNew}>创建工作环境</Button>}</div></div><Mountain/></section><div className="home-split"><section><div className="section-title"><h2>我的工作环境 <small>{data.instances.length}</small></h2><div className="flex">{['全部','运行中','需要处理'].map(value=><button key={value} className={'filter '+(filter===value?'on':'')} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{value}</button>)}</div></div>{list.map(i=><div key={i.id} className={'launch-instance-row '+(current?.id===i.id?'selected':'')}><button className="launch-instance-select" onClick={()=>onSelect(i.id)} aria-pressed={current?.id===i.id}><Logo engine={i.engine}/><span><strong>{i.name}</strong><small>{i.engine} · {i.projectPath.split(/[\\/]/).filter(Boolean).pop()}</small></span></button><span className={'pill '+(needs(i)?'warn':'')}>{needs(i)?'需要处理':runtimeLabels[state(i)?.status??'not_installed']}</span><IconButton icon="settings" label={'管理 '+i.name} onClick={()=>onOpen(i)}/>{runtime(i,true)}</div>)}{!list.length&&<div className="empty"><p>{data.instances.length?'当前分类没有实例。':'还没有工作环境，创建一个开始使用。'}</p>{!data.instances.length&&<Button onClick={onNew}>新建实例</Button>}</div>}<div className="below-list"><I name="shield"/><span>环境彼此独立。尝试新能力之前，先留下一个恢复点。</span></div></section>{current&&<aside className="inspector launch-inspector"><div className="section-title"><h3>当前环境</h3><IconButton icon="external" label={'查看 '+current.name+' 详情'} onClick={()=>onOpen(current)}/></div><div className="detail-summary"><Logo engine={current.engine}/><div><h2>{current.name}</h2><p>独立配置 · 固定组合</p></div></div><div className="fact"><span>引擎</span><span>{current.engine}</span></div><div className="fact"><span>项目</span><span className="path-text">{current.projectPath.split(/[\\/]/).filter(Boolean).pop()}</span></div><div className="fact"><span>模型连接</span><span>{data.connections.find(c=>c.id===current.connectionId)?.name??'尚未绑定'}</span></div>{needs(current)&&<p className="form-error">{!current.projectExists?'项目目录不存在':connectionIssue(current)||state(current)?.error?.message}</p>}{connectionIssue(current)&&<Button primary onClick={()=>onConnections(current)}>{missingConnection(current)?'选择模型连接':'配置模型连接'}</Button>}<Button onClick={()=>onOpen(current)}>管理环境</Button></aside>}</div></>;
}
