import {useReportBusy} from './operationStatus';
import Section from './Section';
import LocalPack from './LocalPack';
import VersionCatalog from './VersionCatalog';
import {useEffect,useRef,useState} from 'react';
import {errorText,type Gateway,type Instance,type InstancePackage,type PackageCatalog,type Recipe,type RestorePoint} from './domain';
import {invoke} from '@tauri-apps/api/core';
import {Button} from './ui';
import type {Draft} from './packEditing';

export function recipeChanges(before:Recipe,after:Recipe,nameOf:(id:string)=>string=id=>id){
 const workshopIds=[...new Set([...(before.workshop??[]),...(after.workshop??[])].map(item=>`${item.kind}/${item.id}`))];
 const workshopChanges=workshopIds.flatMap(id=>{
  const a=before.workshop?.find(item=>`${item.kind}/${item.id}`===id),b=after.workshop?.find(item=>`${item.kind}/${item.id}`===id);
  if(!a)return [`新增工坊资源 ${id} · ${b!.version} · ${b!.commit.slice(0,12)}`];
  if(!b)return [`移除工坊资源 ${id}；本地文件已改动时将停止更新并保留原内容`];
  return JSON.stringify(a)===JSON.stringify(b)?[]:[`更新工坊资源 ${id}：${a.version} / ${a.commit.slice(0,12)} → ${b.version} / ${b.commit.slice(0,12)}（来源或文件清单变化）`];
 });
 const bundleOrder=(recipe:Recipe)=>recipe.extensions.filter(item=>item.id.startsWith('dsh-npm:')).map(item=>item.id.slice(8)).join(' → ');
 const orderChange=[...(before.thinkingLevel!==after.thinkingLevel?[`默认思考强度：${before.thinkingLevel??'不指定'} → ${after.thinkingLevel??'不指定'}（下次启动生效）`]:[]),...workshopChanges,...(bundleOrder(before)!==bundleOrder(after)?[`DSH 外部插件顺序：${bundleOrder(before)||'无'} → ${bundleOrder(after)||'无'}`]:[])];
 const ids=[...new Set([...before.extensions,...after.extensions].map(item=>item.id))];
 const describe=(item:Recipe['extensions'][number]|undefined)=>item?`${item.version} · ${item.enabled?'启用':'禁用'}${item.disabledResources?.length?` · 不加载 ${[...item.disabledResources].sort().join('、')}`:''}${Object.entries(item.resourceRules??{}).sort(([a],[b])=>a.localeCompare(b)).map(([kind,rules])=>` · ${kind} 文件规则：${JSON.stringify(rules)}`).join('')}`:'未安装';
 return [...orderChange,...((before.cover??'')!==(after.cover??'')?['组合封面已修改']:[]),...(before.name!==after.name?[`组合名称：${before.name} → ${after.name}`]:[]),...(before.description!==after.description?['组合简介已修改']:[]),...(before.sourceNote!==after.sourceNote?['公开来源说明已修改']:[]),...(JSON.stringify(before.modelProtocols)!==JSON.stringify(after.modelProtocols)?[`模型协议：${before.modelProtocols.join('、')} → ${after.modelProtocols.join('、')}`]:[]),...(before.profileId!==after.profileId?[`版本组合：${before.profileId} → ${after.profileId}`]:[]),...ids.map(id=>{const a=before.extensions.find(e=>e.id===id),b=after.extensions.find(e=>e.id===id);return describe(a)===describe(b)?null:`${nameOf(id)}：${describe(a)} → ${describe(b)}`;}).filter(Boolean)];
}
type PanelProps={gateway:Gateway;instance:Instance;disabled?:boolean;recoveryOnly?:boolean};
export default function PackagePanel(props:PanelProps){return <InstancePackagePanel key={props.instance.id} {...props}/>;}
function InstancePackagePanel({gateway,instance,disabled=false,recoveryOnly=false}:PanelProps){
 const [data,setData]=useState<InstancePackage>(),[catalog,setCatalog]=useState<PackageCatalog>(),[draft,setDraft]=useState<Recipe>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[portable,setPortable]=useState(''),[message,setMessage]=useState('');
 const [updates,setUpdates]=useState<{id:string;revision:number;recipe:Recipe;ready:boolean}[]>([]),[updateError,setUpdateError]=useState('');
 const exportDetails=useRef<HTMLDivElement>(null);const [exportOpen,setExportOpen]=useState(false);
 const [browseVersions,setBrowseVersions]=useState(false);
 const [restorePreview,setRestorePreview]=useState<RestorePoint>();
 const [trialProfile,setTrialProfile]=useState(instance.profileId),[versions,setVersions]=useState<{id:string;engine:string;dependencies:Record<string,string>}[]>([]);
 useEffect(()=>{if(gateway.mode==='desktop')void invoke<typeof versions>('resolved_profiles').then(setVersions).catch(e=>setError(errorText(e)));},[]);
 const [cloneName,setCloneName]=useState(''),[cloneProject,setCloneProject]=useState('');
 const load=async()=>{const [next,items]=await Promise.all([gateway.instancePackage(instance.id),recoveryOnly?Promise.resolve(undefined):gateway.packageCatalog()]);setData(next);setCatalog(items);if(gateway.mode==='desktop'&&!recoveryOnly){try{setUpdates((await invoke<Draft[]>('pack_drafts')).flatMap(pack=>pack.ready?[pack]:pack.lastReady?.origin?[{...pack,ready:true,recipe:pack.lastReady,revision:pack.lastReady.origin.revision}]:[]));setUpdateError('');}catch(e){setUpdateError(errorText(e));}}};
 useEffect(()=>{void load().catch(e=>setError(errorText(e)));},[instance.id]);
 async function perform(work:()=>Promise<unknown>,success="已保存，下次启动使用此组合。"){setBusy(true);setError('');setMessage('');try{await work();await load();setDraft(undefined);setRestorePreview(undefined);setMessage(success);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 useReportBusy(busy);
 const versionConflicts=draft&&data&&draft.profileId!==data.recipe.profileId?draft.extensions.filter(item=>{const name=item.id.startsWith('dsh-npm:')?item.id.slice(8):item.id.startsWith('npm:')?item.id.slice(4):undefined;if(!name)return false;return versions.find(version=>version.id===draft.profileId)?.dependencies[name]!==item.version;}):[];
 const update=data?.recipe.origin?updates.find(pack=>pack.ready&&pack.id===data.recipe.origin?.id&&pack.revision>data.recipe.origin.revision):undefined;
 if(gateway.mode!=='desktop')return null;
 return <section className="instance-runtime" aria-label="扩展与恢复点">
  <h2>{recoveryOnly?'恢复点':'扩展与组合'}</h2><p className="sub">更改前自动保存恢复点。快照包含组合、实例配置和会话。恢复前再次备份，不覆盖外部项目文件、认证文件或共享密钥。</p>
  {error&&<div className="form-error" role="alert">{error}<Button disabled={busy} onClick={()=>{setBusy(true);setError('');void load().catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}>重新读取实例与恢复点</Button></div>}{message&&<p role="status">{message}</p>}
  {data&&<>
   {!recoveryOnly&&<>
   {data.workshopError&&<p role="alert">工坊资源读取失败：{data.workshopError}</p>}
   {!!data.workshopResources?.length&&<section aria-label="实例工坊资源"><h3>已安装的工坊资源</h3>{data.workshopResources.map(resource=><div className="fact" key={resource.directory}><div><strong>{resource.name}{resource.version?` · ${resource.version}`:''}</strong><p>{resource.directory} · {resource.status}</p>{resource.commit&&<p>来源提交：{resource.commit.slice(0,12)}</p>}</div></div>)}<p>这些目录随新恢复点备份。分享前请用“保存为整合包”校验实际文件并提取固定来源，再从发现整合包导出；下方“导出清单”仅包含当前组合已声明的资源。</p></section>}
   {updateError&&<p role="status">整合包更新读取失败：{updateError} <Button disabled={busy} onClick={()=>void load().catch(e=>setError(errorText(e)))}>重新读取</Button></p>}
   {data.recipe.origin&&<p className="sub">来源组合修订 {data.recipe.origin.revision} · 实例中的调整独立保存</p>}
   {update&&<section aria-label="整合包更新"><h3>{update.recipe.name} 有新修订</h3><p>修订 {data.recipe.origin?.revision} → {update.revision}。查看差异后决定是否更新；不会自动更改此实例。</p>{update.recipe.engine!==instance.engine?<p>新修订已切换引擎，请从整合包创建新实例，当前实例保持原配置。</p>:<Button disabled={busy||disabled} onClick={()=>setDraft(update.recipe)}>查看更新差异</Button>}</section>}
   {data.recipe.extensions.length===0&&<p className="sub">当前没有安装扩展。</p>}
   {data.recipe.extensions.map(item=><div className="fact" key={item.id}><div><strong>{catalog?.extensions.find(e=>e.id===item.id)?.name??item.id}</strong><p className="sub">{item.version} · {item.enabled?'已启用':'已禁用'}</p></div><div className="form-actions"><Button small disabled={busy||disabled} onClick={()=>setDraft({...data.recipe,extensions:data.recipe.extensions.map(e=>e.id===item.id?{...e,enabled:!e.enabled}:e)})}>{item.enabled?'禁用':'启用'}</Button><Button small disabled={busy||disabled} onClick={()=>setDraft({...data.recipe,extensions:data.recipe.extensions.filter(e=>e.id!==item.id)})}>移除</Button>{catalog?.extensions.some(e=>e.id===item.id&&e.version!==item.version)&&<Button small disabled={busy||disabled} onClick={()=>setDraft({...data.recipe,extensions:data.recipe.extensions.map(e=>e.id===item.id?{...e,version:catalog?.extensions.find(entry=>entry.id===item.id)?.version??e.version}:e)})}>更新到 {catalog?.extensions.find(entry=>entry.id===item.id)?.version}</Button>}</div></div>)}
   <p className="sub">分享仅包含受管组件、固定来源和允许公开的配置；项目文件、会话、密钥与本机连接留在本机。自动发现的完整 Skill 可先整理到新组合，其他手动资源请导入并补齐来源。需要保留实例状态时，请使用恢复点。</p>
   <LocalPack id={instance.id} disabled={busy||disabled}/>
   <div className="form-actions"><Button disabled={busy} onClick={()=>void perform(()=>invoke('save_instance_pack',{id:instance.id}),"已保存受管组合，可在发现整合包中编辑或导出分享。此操作不包含项目文件与会话。")}>保存为整合包</Button>{catalog?.packs.filter(p=>p.engine===instance.engine).map(pack=><Button key={pack.name} disabled={busy||disabled} onClick={()=>setDraft(pack)}>选择{pack.name}</Button>)}<Button disabled={busy} onClick={()=>{setPortable(JSON.stringify({...data.recipe,origin:undefined},null,2));setMessage("清单已生成，可在下方复制 JSON。");setExportOpen(true);requestAnimationFrame(()=>exportDetails.current?.scrollIntoView({block:"nearest"}));}}>导出清单</Button></div>
   <div ref={exportDetails}><Section description="用于手动交换配置，不包含密钥与本机路径。" open={exportOpen} onOpenChange={setExportOpen} title={<>导入或复制整合包清单</>}><p className="sub">仅导入已知固定组合；使用此实例已绑定的本机连接。清单不含密钥和本机路径。</p><textarea className="input selectable" aria-label="整合包 JSON 清单" rows={7} value={portable} onChange={e=>setPortable(e.target.value)}/><Button disabled={busy||disabled||!portable.trim()} onClick={()=>{try{const parsed=JSON.parse(portable);if(!parsed||parsed.schemaVersion!==1||typeof parsed.name!=='string'||typeof parsed.engine!=='string'||typeof parsed.profileId!=='string'||!Array.isArray(parsed.modelProtocols)||!Array.isArray(parsed.extensions)||!parsed.extensions.every((item:unknown)=>typeof item==='object'&&item!==null&&'id' in item&&typeof item.id==='string'&&'version' in item&&typeof item.version==='string'&&'enabled' in item&&typeof item.enabled==='boolean'))throw Error('清单格式不正确');setDraft({...parsed,origin:undefined});setError('');}catch{setError('清单格式不正确，请粘贴 schemaVersion 为 1 的整合包 JSON。');}}}>预览导入</Button></Section></div>
   {draft&&<div className="instance-runtime"><h3>确认组合变更</h3>{versionConflicts.length>0&&<p className="form-error" role="alert">目标版本未包含以下精确依赖：{versionConflicts.map(item=>`${item.id} ${item.version}`).join("、")}。请先在目标版本中装配对应扩展。</p>}<p>{draft.name} · {draft.profileId}</p><p className="sub">当前 {data.recipe.extensions.length} 项 → 变更后 {draft.extensions.length} 项。当前实例：{instance.name}。已有模型连接保持绑定。</p>{recipeChanges(data.recipe,draft).map(line=><p key={line}>{line}</p>)}<p className="sub">应用后使用上方完整组合；此实例中单独添加、且新组合没有包含的资源将被移除，请核对差异。更改前自动保存恢复点。</p><p className="sub">内置扩展无安装脚本；工具代码将在引擎中执行。未知来源或跨引擎扩展将被拒绝。</p><div className="form-actions"><Button onClick={()=>setDraft(undefined)} disabled={busy}>取消</Button><Button primary disabled={busy||disabled||versionConflicts.length>0} onClick={()=>void perform(()=>draft.profileId===instance.profileId?gateway.changePackage(instance.id,draft,false,data.recipe):gateway.installPackage(instance.id,draft,false,data.recipe))}>{draft.profileId===instance.profileId?'保存组合':'安装目标版本并切换'}</Button></div></div>}
   <Section description={<>当前使用 {instance.profileId}，更换前可预览差异。</>} title={<>版本与组件</>}><p>当前版本：{instance.profileId}</p><p className="sub">先安装目标版本，成功后切换；切换前保存恢复点。保留当前扩展和模型连接，扩展依赖不匹配时会拒绝变更。</p><label className="field"><span>目标版本</span><select className="input" disabled={busy||disabled} value={trialProfile} onChange={e=>setTrialProfile(e.target.value)}><option value={instance.profileId}>当前 · {instance.profileId}</option>{catalog?.packs.filter(pack=>pack.engine===instance.engine&&pack.profileId!==instance.profileId).map(pack=><option key={pack.profileId} value={pack.profileId}>{pack.profileId}</option>)}{versions.filter(version=>version.engine===instance.engine&&version.id!==instance.profileId).map(version=><option key={version.id} value={version.id}>{Object.entries(version.dependencies).map(([name,value])=>`${name} ${value}`).join(' / ')}</option>)}</select></label><Button disabled={busy||disabled} onClick={()=>setBrowseVersions(!browseVersions)}>{browseVersions?'收起版本目录':'浏览其他版本'}</Button>{browseVersions&&<VersionCatalog engine={instance.engine} onSelected={id=>{setTrialProfile(id);void invoke<typeof versions>('resolved_profiles').then(setVersions).catch(e=>setError(errorText(e)));setBrowseVersions(false);}}/>}<Button disabled={busy||disabled||trialProfile===instance.profileId} onClick={()=>setDraft({...data.recipe,profileId:trialProfile})}>预览版本变更</Button></Section>
   <Section description="新建独立实例，复用模型连接；保留原实例。" title={<>克隆实例配置</>}><p className="sub">沿用模型连接引用，不复制密钥或对话。项目文件不会复制；选择相同目录时，两实例会操作同一份项目文件。</p><label className="field"><span>新实例名称</span><input className="input" value={cloneName} onChange={e=>setCloneName(e.target.value)}/></label><label className="field"><span>试用版本组合</span><select className="input" value={trialProfile} onChange={e=>setTrialProfile(e.target.value)}><option value={instance.profileId}>沿用当前版本 · {instance.profileId}</option>{catalog?.packs.filter(pack=>pack.engine===instance.engine&&pack.profileId!==instance.profileId).map(pack=><option key={pack.profileId} value={pack.profileId}>{pack.profileId}</option>)}{versions.filter(version=>version.engine===instance.engine&&version.id!==instance.profileId).map(version=><option key={version.id} value={version.id}>{Object.entries(version.dependencies).map(([name,value])=>`${name} ${value}`).join(' / ')}</option>)}</select></label><p className="sub">版本不包含现有扩展所需依赖时会拒绝创建，不会静默移除扩展。新实例需单独安装和启动，原实例保持原版本。</p><div className="fact"><span className="path-text">{cloneProject||'请选择项目目录'}</span><Button disabled={busy} onClick={()=>void gateway.pickProject().then(path=>{if(path)setCloneProject(path);}).catch(e=>setError(errorText(e)))}>选择目录</Button></div><Button disabled={busy||(disabled&&trialProfile===instance.profileId)||!cloneName.trim()||!cloneProject} onClick={()=>void perform(()=>trialProfile===instance.profileId?gateway.cloneInstance(instance.id,cloneName,cloneProject):invoke('clone_version_trial',{id:instance.id,name:cloneName,projectPath:cloneProject,profileId:trialProfile}),`已克隆为“${cloneName}”，可在我的实例中查看。`)}>克隆配置</Button></Section>
   </>}
   {disabled&&recoveryOnly&&<p className="notice">请先在实例页停止工作台，再创建或恢复快照。</p>}
   {restorePreview&&<section className="instance-runtime"><h3>恢复预览</h3><p>{new Date(restorePreview.createdAt*1000).toLocaleString()} · {restorePreview.reason}</p>{recipeChanges(data.recipe,restorePreview.recipe).map(line=><p key={line}>{line}</p>)}<p className="sub">{restorePreview.dataVersion===2?'将恢复配置、会话、工作区状态和工坊资源目录。':restorePreview.dataVersion===1?'将恢复配置、会话和工作区状态；保留当前工坊资源目录。':'此旧恢复点仅恢复组合配置。'}当前状态会先备份；外部项目文件和认证文件保持不变。</p><div className="form-actions"><Button disabled={busy} onClick={()=>setRestorePreview(undefined)}>取消</Button><Button primary disabled={busy||disabled} onClick={()=>void perform(()=>gateway.restorePackage(instance.id,restorePreview.id),"已恢复此快照，恢复前的状态已自动备份。")}>备份当前状态并恢复</Button></div></section>}
   <Section collapsible={!recoveryOnly} title={<>恢复点 · {data.restorePoints.length}</>}><Button disabled={busy||disabled} onClick={()=>void perform(()=>gateway.restorePackage(instance.id,null),"恢复点已创建，可在下方列表中查看。")}>创建恢复点</Button>{data.restorePoints.length===0&&<p>还没有恢复点。可以先创建一个；之后修改组合前也会自动保存。</p>}{data.restorePoints.map(point=><div className="fact" key={point.id}><div>{point.reason}<p className="sub">{new Date(point.createdAt*1000).toLocaleString()} · {point.recipe.extensions.length} 项扩展</p></div><Button small disabled={busy||disabled} onClick={()=>setRestorePreview(point)}>恢复此快照</Button></div>)}</Section>
  </>}
 </section>;
}
