import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {isNative} from './native';
import {Button} from './ui';
type Source={id:string;label:string;package:string;entries:{version:string;preview:boolean;runtime:string;integrity:string;artifact:string;releaseUrl:string;piDependency:string}[];syncedAt:number;githubComplete:boolean;error?:string};
type Plan={engine:string;version:string;dependencies:Record<string,string>;runtime:string;warnings:string[]};
export default function VersionCatalog({engine,onSelected}:{engine?:string;onSelected?:(id:string)=>void}){
 const [plan,setPlan]=useState<Plan>();
 const previewRequest=useRef(0);
 const [operation,setOperation]=useState(''),[cancelling,setCancelling]=useState(false);
 const [planSource,setPlanSource]=useState(''),[lockedId,setLockedId]=useState('');
 async function lock(){if(!plan||busy)return;const operationId=crypto.randomUUID();setOperation(operationId);setCancelling(false);setBusy(true);setError('');try{const id=await invoke<string>('lock_version_plan',{sourceId:planSource,version:plan.version,operationId});setLockedId(id);onSelected?.(id);}catch(e){setError(String(e));}finally{setBusy(false);setOperation('');setCancelling(false);}}
 async function resolve(sourceId:string,version:string){const request=++previewRequest.current;setError('');setLockedId('');setPlan(undefined);try{const next=await invoke<Plan>('resolve_version_plan',{sourceId,version});if(request!==previewRequest.current)return;setPlanSource(sourceId);setPlan(next);}catch(e){if(request===previewRequest.current)setError(String(e));}}
 const [sourceId,setSourceId]=useState('');
 const [sources,setSources]=useState<Source[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[preview,setPreview]=useState(false),[limit,setLimit]=useState(30);
 async function load(refresh=false){setBusy(true);setError('');try{setSources(await invoke<Source[]>('version_catalog',{refresh}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 useEffect(()=>{if(isNative)void load();return()=>{previewRequest.current++;};},[]);
 const applicable=sources.filter(source=>!engine||(engine==='DSH'?source.package.includes('deepseek'):!source.package.includes('deepseek')));
 const shown=applicable.filter(source=>source.id===(sourceId||applicable[0]?.id));
 return <section className="instance-runtime"><div className="section-title"><h2>引擎版本目录</h2><Button disabled={busy||!isNative} onClick={()=>void load(true)}>{busy?'正在同步…':'刷新来源'}</Button></div><p>查看 GitHub 发行版、标签与 npm 历史版本。当前实例仍使用固定组合；目录收录不代表已验证兼容。</p>
 {!isNative&&<p>请在桌面端读取真实版本目录。</p>}{error&&<p role="alert" className="form-error">{error}</p>}
 <label className="field"><span>组件</span><select className="input" value={sourceId||applicable[0]?.id||''} onChange={e=>{setSourceId(e.target.value);setPlan(undefined);}}>{applicable.map(source=><option key={source.id} value={source.id}>{source.label}</option>)}</select></label><label className="field"><span>搜索版本</span><input className="input" value={query} onChange={e=>{setQuery(e.target.value);setLimit(30);}} placeholder="例如 0.9.3"/></label><label><input type="checkbox" checked={preview} onChange={e=>setPreview(e.target.checked)}/> 包含预览版</label>
 {plan&&<section className="instance-runtime" aria-label="版本组合预览"><h3>{plan.engine} · {plan.version}</h3><p>运行条件：Node {plan.runtime}</p>{Object.entries(plan.dependencies).map(([name,version])=><p key={name}>{name} @ {version}</p>)}{plan.warnings.map(warning=><p key={warning}>{warning}</p>)}<p>锁定会解析精确依赖，不执行安装脚本，不修改现有实例。</p><Button disabled={busy||!!lockedId} onClick={()=>void lock()}>{busy?'正在解析依赖…':'锁定此组合'}</Button>{operation&&<Button disabled={cancelling} onClick={()=>{setCancelling(true);void invoke('cancel_version_plan',{operationId:operation}).catch(e=>{setError(String(e));setCancelling(false);});}}>{cancelling?'正在取消…':'取消解析'}</Button>}{lockedId&&<p role="status">组合已锁定：{lockedId}。可在创建实例或克隆试用时选择此版本组合。</p>}<Button disabled={busy} onClick={()=>setPlan(undefined)}>收起预览</Button></section>}{shown.map(source=>{const matches=source.entries.filter(e=>(preview||!e.preview)&&e.version.includes(query));return <section key={source.id}><h3>{source.label} · {source.package}</h3><p>{source.syncedAt?`缓存更新于 ${new Date(source.syncedAt*1000).toLocaleString()}`:'尚未同步'}</p><p>{source.githubComplete?'GitHub 发行版与标签已同步':'GitHub 目录尚未同步完整'}</p>{source.error&&<p role="status">{source.error}；{source.entries.length?'显示上次缓存':'暂无可用目录'}。</p>}{matches.slice(0,limit).map(entry=><div className="fact" key={entry.version}><strong>{entry.version}</strong><span>{entry.preview?'预览版':'正式版'} · Node {entry.runtime} · {entry.artifact?'有 npm 工件，兼容性待解析':'仅标签，暂无可安装 npm 工件'}{entry.piDependency&&` · Pi 依赖 ${entry.piDependency}`}</span><Button disabled={busy||!entry.artifact} onClick={()=>void resolve(source.id,entry.version)}>预览组合</Button></div>)}{!busy&&!matches.length&&<p>{!preview&&source.entries.some(entry=>entry.preview)?<>该来源的可选版本包含预览版。<Button onClick={()=>setPreview(true)}>显示预览版</Button></>:'没有匹配版本。'}</p>}{matches.length>limit&&<Button onClick={()=>setLimit(n=>n+30)}>加载更多（共 {matches.length} 项）</Button>}</section>;})}
 </section>;
}
