import {useReportBusy} from './operationStatus';
import Section from './Section';
import {useEffect,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {errorText,type Instance,type WorkshopRef} from './domain';
import {Button} from './ui';
type Plan={id:string;name:string;version:string;directory:string;commit:string;activation:string;hostPackage?:string;files:{path:string;url:string}[];requires:unknown};
export default function WorkshopAssetPanel({resourceId,instances,onClose,onAdd,onBusyChange}:{resourceId:string;instances:Instance[];onClose:()=>void;onAdd?:(resource:WorkshopRef)=>void;onBusyChange?:(busy:boolean)=>void}){
 const [downloadId,setDownloadId]=useState(''),[cancelling,setCancelling]=useState(false);
 const [plan,setPlan]=useState<Plan>(),[target,setTarget]=useState(''),[busy,setBusy]=useState(true),[cached,setCached]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useReportBusy(busy);
 useEffect(()=>{onBusyChange?.(busy);},[busy,onBusyChange]);
 useEffect(()=>{let active=true;setBusy(true);void invoke<Plan>('preview_workshop_asset',{resourceId}).then(value=>{if(active)setPlan(value);}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[resourceId]);
 async function refreshPlan(){if(busy)return;setBusy(true);setError('');setNotice('正在刷新工坊目录，当前组合选择保留。');try{const catalog=await invoke<{errors:string[]}>('workshop_catalog',{refresh:true});if(catalog.errors.length)throw new Error(catalog.errors.join('；'));const value=await invoke<Plan>('preview_workshop_asset',{resourceId});setPlan(value);setCached(false);setNotice('资源计划已更新，请重新下载或验证缓存。');}catch(e){setError(errorText(e));setNotice('');}finally{setBusy(false);}}
 async function download(){if(!plan||busy)return;setBusy(true);setError('');setNotice('');const operationId=crypto.randomUUID();setDownloadId(operationId);setCancelling(false);try{const result=await invoke<{plan:Plan}>('download_workshop_asset',{resourceId,operationId});if(result.plan.commit!==plan.commit)throw new Error('来源提交已变化，请关闭预览后重新选择资源。');setCached(true);setNotice('完整资源已缓存，尚未写入实例。');}catch(e){setError(errorText(e));}finally{setBusy(false);setDownloadId('');setCancelling(false);}}
 async function cancelDownload(){if(!downloadId||cancelling)return;setCancelling(true);try{await invoke('cancel_workshop_download',{operationId:downloadId});setNotice('正在取消，等待当前网络读取结束；已有缓存保留。');}catch(e){setError(errorText(e));setCancelling(false);}}
 async function add(){if(!plan||!onAdd||busy)return;setBusy(true);setError('');try{const reference=await invoke<WorkshopRef>('workshop_asset_reference',{resourceId,expectedCommit:plan.commit});onAdd(reference);setNotice('已加入当前组合；保存前可以继续调整，不会修改实例。');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function install(){if(!plan||!target||busy)return;setBusy(true);setError('');try{await invoke('install_workshop_asset',{id:target,resourceId,expectedCommit:plan.commit});setNotice(`已安装到“${instances.find(item=>item.id===target)?.name??target}”，安装前已创建恢复点。${plan.activation}。`);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <section className="instance-runtime" aria-label="工坊资源安装预览"><div className="section-title"><h3>{plan?`${plan.name} · ${plan.version}`:'读取资源计划'}</h3><Button disabled={busy} onClick={onClose}>关闭预览</Button></div>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{!plan&&error&&<Button disabled={busy} onClick={()=>void refreshPlan()}>{busy?'正在刷新…':'刷新工坊并重试'}</Button>}{plan&&<><p>{plan.activation}。安装文件不会自动切换当前主题或启用预设。</p><p>所需宿主：{plan.hostPackage??(plan.directory.startsWith('skins/')?'@linxin666/dsh-client-ui-skin-center':plan.directory.startsWith('pets/')?'@linxin666/dsh-pet':'@linxin666/dsh-client-ui-preset-center')}。请先在扩展市场安装并启用兼容版本；也可使用包含该组件的全家桶。</p><p>共 {plan.files.length} 个文件 · 固定提交 {plan.commit.slice(0,12)}</p>{!onAdd&&<><label className="field"><span>安装到 DSH 实例</span><select className="input" disabled={busy} value={target} onChange={e=>{setTarget(e.target.value);setNotice('');}}><option value="">选择目标实例</option>{instances.filter(item=>item.engine==='DSH').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><p>请先停止目标实例，并安装对应宿主插件。同名资源存在时保留原内容；安装前自动备份，可从恢复中心撤回。</p></>}<div className="form-actions resource-confirm-actions"><Button disabled={busy||cached} onClick={()=>void download()}>{downloadId?'正在下载并校验…':cached?'缓存已校验':'下载或验证缓存'}</Button>{downloadId&&<Button disabled={cancelling} onClick={()=>void cancelDownload()}>{cancelling?'正在取消…':'取消下载'}</Button>}{onAdd?<Button primary disabled={busy||!cached} onClick={()=>void add()}>加入当前组合</Button>:<Button primary disabled={busy||!cached||!target} onClick={()=>void install()}>{busy&&cached?'正在安装…':'备份并安装到所选实例'}</Button>}</div><Section description="核对安装路径、宿主声明与完整文件清单。" title={<>文件与宿主要求</>}><p>实例内目录：{plan.directory}</p><pre className="selectable">{JSON.stringify(plan.requires,null,2)}</pre><ul>{plan.files.map(file=><li key={file.path}>{file.path}</li>)}</ul></Section></>}</section>;
}
